### ISSUE TITLE
Error in `BufferDict.del_distribution`

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#19]
The following does not work with `gvar` 11.9.5:

```python
import gvar
gvar.BufferDict.add_distribution('cippa', gvar.exp)
gvar.BufferDict.del_distribution('cippa')
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_bufferdict.pyx", line 539, in gvar._bufferdict.BufferDict.del_distribution
AttributeError: 'cython_function_or_method' object has no attribute 'invfcn'
```

**Comment by gplepage** [comment]
This is a bug. I'll fix it shortly.

**Comment by gplepage** [comment]
Fixed in version 11.9.6.

**Comment by Gattocrucco** [comment]
Thanks for the immediate fix.
